In [1]:
s="Hi there sam";
s=s.split()
print(s);

['Hi', 'there', 'sam']


In [2]:
planet="Earth"
diameter=12742
print('The diameter of {} is {} kilometers.'. format (planet,diameter));

The diameter of Earth is 12742 kilometers.


In [8]:
d = { 'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
lst= [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


In [9]:
import numpy as np 
array=np.zeros(10)
print("An array of 10zero")
print(array)

An array of 10zero
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the event integers from 20 to 35")
print(array)

Array of all the event integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [12]:
import numpy as np
x=np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
import numpy as np
a=np.array ([1,2,3])
b=np.array ([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [15]:
import pandas as pd
data=[['TOM', 20],['NICK', 21],['KRISH', 16],['JACK', 18]]
df = pd.DataFrame(data, columns=['name', 'Age'])
df

name  Age
0    TOM   20
1   NICK   21
2  KRISH   16
3   JACK   18

In [16]:
import pandas as pd 
dRan1=pd.date_range(start='1-1-2023',periods=41)
print(dRan1)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


In [18]:
import pandas as pd
import numpy as np
list=[[1, 'aaa', 22],[2, 'bbb', 25],[3, 'ccc', 23]]
list={'name':['aaa','bbb','ccc'],'points':[22,25,23]}
df = pd.DataFrame(list,index=['1','2','3'])
df

name  points
1  aaa      22
2  bbb      25
3  ccc      23